In [3]:
import os

import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(tf.version.VERSION)
from keras.models import load_model

model = load_model('/Users/manideepguntuku/DataspellProjects/FOG Project/Face_trained_model_00_21_06_.h5')

df = pd.read_csv('faces.csv', index_col=0)

X = df.iloc[:, :100 * 100].values.reshape(-1, 100, 100, 1)
y = df.iloc[:, -1].values
X.shape, y.shape
num_classes = 3
print(X.shape)

print(X)
model.predict(X)

2.12.0
(15, 100, 100, 1)
[[[[ 46]
   [ 45]
   [ 46]
   ...
   [ 37]
   [ 37]
   [ 44]]

  [[183]
   [188]
   [185]
   ...
   [114]
   [132]
   [ 47]]

  [[187]
   [182]
   [184]
   ...
   [121]
   [136]
   [ 45]]

  ...

  [[196]
   [196]
   [195]
   ...
   [148]
   [135]
   [ 46]]

  [[196]
   [196]
   [194]
   ...
   [121]
   [148]
   [ 46]]

  [[196]
   [195]
   [194]
   ...
   [125]
   [169]
   [  0]]]


 [[[129]
   [116]
   [105]
   ...
   [252]
   [249]
   [162]]

  [[138]
   [126]
   [111]
   ...
   [251]
   [250]
   [160]]

  [[162]
   [162]
   [156]
   ...
   [249]
   [252]
   [210]]

  ...

  [[250]
   [251]
   [252]
   ...
   [251]
   [251]
   [251]]

  [[251]
   [251]
   [251]
   ...
   [251]
   [251]
   [253]]

  [[253]
   [252]
   [251]
   ...
   [251]
   [251]
   [  0]]]


 [[[ 92]
   [ 87]
   [ 80]
   ...
   [ 48]
   [ 58]
   [ 93]]

  [[164]
   [165]
   [124]
   ...
   [120]
   [138]
   [ 94]]

  [[167]
   [126]
   [ 99]
   ...
   [131]
   [ 95]
   [ 84]]

  ...

  [[1

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)